### ISSUE TITLE
Fields need to be populated for SO and SO_LN

### ISSUE THREAD

**Issue by kentbower** [kbower/tickettest1#173]
_Imported from trac ticket 173.
Created by **kbower**
Opened in trac: May 13, 2010, 9:37:07 AM
Last modified in trac: Oct 14, 2010, 1:43:22 PM_
***
_by kbower:_
According to Waynes email, we should also be populating the following columns in SALES.SO and SALES.SO_LN:

### SO

~~EMP_CD_OP~~
~~EMP_CD_KEYER~~
~~FIN_CUST_CD~~ - When we get to finance Sales - will map this only to the table
~~SHIP_TO_ST_CD~~
~~SHIP_TO_ZONE_CD~~
~~TAX_CD - When we address tax codes~~
~~ORD_SRT_CD - We need as an added entry~~
~~SHIP_TO_TITLE~~ Ignoring this
~~SHIP_TO_F_NAME~~
~~SHIP_TO_L_NAME~~
~~SHIP_TO_ADDR1~~
~~SHIP_TO_ADDR2~~
~~SHIP_TO_ZIP_CD~~
~~SHIP_TO_H_PHONE~~
~~SHIP_TO_B_PHONE~~
~~SHIP_TO_EXT~~
~~SHIP_TO_CITY~~
~~PCT_OF_SALE2~~
~~SO_WR_SEC~~
SHIP_TO_CUST_CD -- Needs to be it's own thing, big implications with this one
~~DEL_CHG~~
~~SETUP_CHG~~
~~TAX_CHG - When we address taxes~~
~~LAWAWAY~~ Added to table and query only
~~CASH_AND_CARRY~~ Added to table and query only

### SO_LN

~~COMM_CD from ITM.COMM_CD~~
~~SPIFF~~
~~TAKEN_WITH~~ only added db cols
~~SET_UP~~ only added db cols
~~PU_DISC_AMT~~ only added db cols
~~SO_EMP_SLSP_CD1~~
~~SO_EMP_SLSP_CD2~~
~~PCT_OF_SALE1~~
~~PCT_OF_SALE2~~
~~COMM_ON_SETUP_CHG~~ Only added db cols
~~COMM_ON_DEL_CHG~~ Only added db cols
~~DELIVERY_POINTS~~

Also copy salespersons and percentages of sale from header.

see [#176](176)

**Comment by kentbower** [comment]
_**rneville** trac comment on May 13, 2010, 2:05:32 PM:_

accepted

**Comment by kentbower** [comment]
_**rneville** trac comment on Oct 14, 2010, 1:43:22 PM:_

(In [[818]](../commit/e51fc26a9f5cd9a15552b5779c21b44e328843dd))
closes #173

**Comment by kbower** [comment]
_**rneville** trac status change on Oct 14, 2010, 1:43:22 PM:_ **closed**
