### ISSUE TITLE
Amount left for allocation on split payment is not updated correctly

### ISSUE THREAD

**Issue by kbower** [kbower/tickettest1#249]
_Imported from trac ticket 249.
Created by **kbower**
Opened in trac: Jul 31, 2010, 12:06:50 PM
Last modified in trac: Aug 2, 2010, 2:33:23 PM_
***

**Comment by kentbower** [comment]
_**rneville** trac comment on Aug 2, 2010, 2:33:23 PM:_

(In [[733]](../commit/5c77abc1d3b49c0fa840102c4d6aa27096b54077))
fixes #249

**Comment by kentbower** [comment]
_**rneville** trac status change on Aug 2, 2010, 2:33:23 PM:_ **closed**
