### ISSUE TITLE
Change of customer fields is not recorded when saving with new order

### ISSUE THREAD

**Issue by kentbower** [kbower/tickettest1#788]
_Imported from trac ticket 788.
Created by **kbower**
Opened in trac: Mar 5, 2011, 9:16:09 PM
Last modified in trac: May 9, 2011, 4:55:38 PM_
***
_by kbower:_
Because logic skips all order comments for new order save.

**Comment by kentbower** [comment]
_**sshah** trac comment on May 9, 2011, 4:15:12 PM:_

(Changeset [[1438]](../commit/3af3a4445e8bde49b387af688afce36731eb83e8))
Fixes #788, [#836](836), [#803](803) Adding Order Comments at multiple events eg.(saving new order with changes to customer, making finance payment, changing discounts)

**Comment by kbower** [comment]
_**sshah** trac status change on May 9, 2011, 4:15:12 PM:_ **closed**

**Comment by kbower** [comment]
_**sshah** trac comment on May 9, 2011, 4:55:38 PM:_

(Changeset [[1439]](../commit/6539b1d1bd7117726b372559f3a8d187665caaa9))
Fixes #788, [#803](803). Added check that if adding new customer then dont write order comment, discount on a particular line should record comment correctly.
